version: '2'
services:
  seed:
    image: tatyanayavkina/akka-cluster-with-singleton-test:latest
    ports:
      - '2551:2551'
    environment:
      CLUSTER_PORT: 2551
      CLUSTER_IP: seed
      SEED_PORT_2551_TCP_ADDR: seed
      RABBIT_IP: rabbitmq
    links:
      - rabbitmq
  c1:
    image: tatyanayavkina/akka-cluster-with-singleton-test:latest
    ports:
      - '2552:2552'
    environment:
      CLUSTER_PORT: 2552
      CLUSTER_IP: c1
      SEED_PORT_2551_TCP_ADDR: seed
      RABBIT_IP: rabbitmq
    links:
      - rabbitmq
  c2:
    image: tatyanayavkina/akka-cluster-with-singleton-test:latest
    ports:
      - '2553:2553'
    environment:
      CLUSTER_PORT: 2553
      CLUSTER_IP: c2
      SEED_PORT_2551_TCP_ADDR: seed
      RABBIT_IP: rabbitmq
    links:
      - rabbitmq
  rabbitmq:
   image: rabbitmq:3-management
   ports:
    - '8080:15672'
    - '5672:5672'
