version: '2'
services:
  seed1:
    image: tatyanayavkina/akka-cluster-with-singleton-test:latest
    command: "-Dakka.remote.netty.tcp.hostname=seed1"
    environment:
      RABBIT_IP: rabbitmq
    links:
      - rabbitmq
  seed2:
    image: tatyanayavkina/akka-cluster-with-singleton-test:latest
    command: "-Dakka.remote.netty.tcp.hostname=seed2"
    environment:
      RABBIT_IP: rabbitmq
    links:
      - rabbitmq
  seed3:
    image: tatyanayavkina/akka-cluster-with-singleton-test:latest
    command: "-Dakka.remote.netty.tcp.hostname=seed3"
    environment:
      RABBIT_IP: rabbitmq
    links:
      - rabbitmq
  theone:
    image: tatyanayavkina/akka-cluster-with-singleton-test:latest
    command: "-Dakka.remote.netty.tcp.hostname=theone"
    environment:
      RABBIT_IP: rabbitmq
    links:
      - rabbitmq
      - seed1
      - seed2
      - seed3
  rabbitmq:
   image: rabbitmq:3-management
   ports:
    - '8080:15672'
    - '5672:5672'
